import React from "react"
import { MobileNavigationHeader } from "./sidebar-navigation-base"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  MobileNavigationHeader,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1158%3A90768",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "open": figma.boolean('Open'),
      // "style": figma.enum('Style', {
      //   "Simple": "simple",
      //   "Dual-tier": "dual-tier",
      //   "Slim": "slim",
      //   "Sections dividers": "sections-dividers",
      //   "Sections subheadings": "sections-subheadings"
      // }),
      // "breakpoint": figma.enum('Breakpoint', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => <MobileNavigationHeader />,
  },
)
