import React from "react"
import { AvatarAddButton } from "./avatar-add-button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarAddButton,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1102%3A4864",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        xs: "xs",
        sm: "sm",
        md: "md",
      }),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Focus": "focus",
      //   "Disabled": "disabled"
      // })
    },
    example: (props) => <AvatarAddButton size={props.size} />,
  },
)
