import React from "react"
import { AvatarCompanyIcon } from "./avatar-company-icon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarCompanyIcon,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1036%3A4",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
        "2xl": "2xl",
      }),
    },
    example: (props) => (
      <AvatarCompanyIcon size={props.size} src={/* TODO */} />
    ),
  },
)
