import React from "react"
import { RadioGroup } from "./radio-buttons"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1142%3A87213",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
      }),
      // No matching props could be found for these Figma properties:
      // "type": figma.enum('Type', {
      //   "Icon simple": "icon-simple",
      //   "Icon card": "icon-card",
      //   "Avatar": "avatar",
      //   "Payment icon": "payment-icon",
      //   "Radio button": "radio-button",
      //   "Checkbox": "checkbox"
      // }),
      // "breakpoint": figma.enum('Breakpoint', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => <RadioGroup size={props.size} />,
  },
)
