import React from "react"
import { LoadingIndicator } from "./loading-indicator"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  LoadingIndicator,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1192%3A610",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      type: figma.enum("Style", {
        "Line simple": "line-simple",
        "Line spinner": "line-spinner",
        "Dot circle": "dot-circle",
      }),
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
      }),
      // No matching props could be found for these Figma properties:
      // "supportingText": figma.boolean('Supporting text')
    },
    example: (props) => (
      <LoadingIndicator type={props.type} size={props.size} />
    ),
  },
)
