import React from "react"
import { NavItemButton } from "./nav-item-button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  NavItemButton,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1165%3A736",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      current: figma.boolean("Current"),
      size: figma.enum("Size", {
        md: "md",
        lg: "lg",
      }),
      // No matching props could be found for these Figma properties:
      // "iconSwap": figma.instance('🔀 Icon swap'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Focused": "focused"
      // })
    },
    example: (props) => (
      <NavItemButton
        label={/* TODO */}
        icon={/* TODO */}
        current={props.current}
        size={props.size}
      />
    ),
  },
)
