import React from "react"
import { Dropdown } from "./dropdown"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Dropdown,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=3281%3A383083",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "type": figma.enum('Type', {
      //   "Button": "button",
      //   "Icon": "icon",
      //   "Avatar": "avatar"
      // }),
      // "open": figma.boolean('Open')
    },
    example: (props) => <Dropdown />,
  },
)
