import React from "react"
import { Tag } from "./tags"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=3307%3A417515",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      dot: figma.enum("Icon", {
        Dot: true,
      }),
      // No matching props could be found for these Figma properties:
      // "flagSwap": figma.instance('🔀 Flag swap'),
      // "size": figma.enum('Size', {
      //   "sm": "sm",
      //   "md": "md",
      //   "lg": "lg"
      // }),
      // "action": figma.enum('Action', {
      //   "X close": "x-close",
      //   "Text only": "text-only",
      //   "Count": "count"
      // }),
      // "checkbox": figma.boolean('Checkbox')
    },
    example: (props) => <Tag dot={props.dot} />,
  },
)
