import React from "react"
import { AvatarLabelGroup } from "./avatar-label-group"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarLabelGroup,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=82%3A2793",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
      }),
      status: figma.enum("Status icon", {
        "Online indicator": "offline",
      }),
      verified: figma.enum("Status icon", {
        Verified: true,
      }),
    },
    example: (props) => (
      <AvatarLabelGroup
        size={props.size}
        title={/* TODO */}
        subtitle={/* TODO */}
        status={props.status}
        verified={props.verified}
      />
    ),
  },
)
