import React from "react"
import { Avatar } from "./avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=19%3A1012",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
        "2xl": "2xl",
      }),
      status: figma.enum("Status icon", {
        "Online indicator": "offline",
      }),
      verified: figma.enum("Status icon", {
        Verified: true,
      }),
      placeholder: figma.enum("Placeholder", {
        False: false,
        True: true,
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.boolean('Text')
    },
    example: (props) => (
      <Avatar
        size={props.size}
        status={props.status}
        verified={props.verified}
        placeholder={props.placeholder}
      />
    ),
  },
)
