import React from "react"
import { BadgeGroup } from "./badge-groups"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BadgeGroup,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1046%3A8088",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        md: "md",
        lg: "lg",
      }),
      color: figma.enum("Color", {
        Brand: "brand",
        Warning: "warning",
        Error: "error",
        Gray: "gray",
        Success: "success",
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.boolean('Icon'),
      // "badge": figma.enum('Badge', {
      //   "Leading": "leading",
      //   "Trailing": "trailing"
      // }),
      // "type": figma.enum('Type', {
      //   "Pill color": "pill-color",
      //   "Badge modern": "badge-modern"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover"
      // })
    },
    example: (props) => (
      <BadgeGroup
        addonText={/* TODO */}
        size={props.size}
        color={props.color}
      />
    ),
  },
)
