import React from "react"
import { Badge } from "./badges"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1046%3A3819",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      type: figma.enum("Type", {
        "Pill color": "color",
        "Badge modern": "modern",
      }),
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      color: figma.enum("Color", {
        Gray: "gray",
        Brand: "brand",
        Error: "error",
        Warning: "warning",
        Success: "success",
        "Gray blue": "gray-blue",
        "Blue light": "blue-light",
        Blue: "blue",
        Indigo: "indigo",
        Purple: "purple",
        Pink: "pink",
        Orange: "orange",
      }),
      // No matching props could be found for these Figma properties:
      // "flagSwap": figma.instance('🔀 Flag swap'),
      // "iconTrailingSwap": figma.instance('🔀 Icon trailing swap'),
      // "iconLeadingSwap": figma.instance('🔀 Icon leading swap'),
      // "icon": figma.enum('Icon', {
      //   "False": "false",
      //   "Dot": "dot",
      //   "Country": "country",
      //   "X close": "x-close",
      //   "Avatar": "avatar",
      //   "Icon trailing": "icon-trailing",
      //   "Icon leading": "icon-leading",
      //   "Only": "only"
      // })
    },
    example: (props) => (
      <Badge type={props.type} size={props.size} color={props.color} />
    ),
  },
)
