import React from "react"
import { DropdownMenuSimple } from "./dropdown-header-navigation"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  DropdownMenuSimple,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1288%3A26576",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "open": figma.boolean('Open'),
      // "mobileSubnavOpen": figma.boolean('Mobile subnav open'),
      // "type": figma.enum('Type', {
      //   "Simple": "simple",
      //   "Featured card": "featured-card",
      //   "Simple with footer": "simple-with-footer",
      //   "2-col with links and footer": "2-col-with-links-and-footer",
      //   "Simple 2-col": "simple-2-col",
      //   "Featured posts": "featured-posts",
      //   "Simple 2-col with footer": "simple-2-col-with-footer",
      //   "Floating featured card": "floating-featured-card",
      //   "Floating 2-col with links and footer": "floating-2-col-with-links-and-footer",
      //   "Floating simple with footer": "floating-simple-with-footer"
      // }),
      // "breakpoint": figma.enum('Breakpoint', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => <DropdownMenuSimple />,
  },
)
