import React from "react"
import { Tooltip } from "./tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1052%3A489",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "supportingText": figma.boolean('Supporting text'),
      // "arrow": figma.enum('Arrow', {
      //   "None": "none",
      //   "Bottom left": "bottom-left",
      //   "Bottom right": "bottom-right",
      //   "Left": "left",
      //   "Right": "right",
      //   "Bottom center": "bottom-center",
      //   "Top center": "top-center"
      // })
    },
    example: (props) => <Tooltip title={/* TODO */} />,
  },
)
