import React from "react"
import { Select } from "./select"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Select,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=3281%3A377673",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      isOpen: figma.enum("State", {
        Open: true,
      }),
      isRequired: figma.boolean("↳ Required *"),
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label'),
      // "hintText": figma.boolean('Hint text'),
      // "supportingText": figma.boolean('Supporting text'),
      // "scrollBar": figma.boolean('Scroll bar'),
      // "iconSwap": figma.instance('🔀 Icon swap'),
      // "required": figma.boolean('↳ Required *'),
      // "helpIcon": figma.boolean('↳ Help icon'),
      // "shortcut": figma.boolean('Shortcut'),
      // "type": figma.enum('Type', {
      //   "Default": "default",
      //   "Icon leading": "icon-leading",
      //   "Avatar leading": "avatar-leading",
      //   "Dot leading": "dot-leading",
      //   "Search": "search",
      //   "Tags": "tags"
      // })
    },
    example: (props) => (
      <Select
        isDisabled={props.isDisabled}
        isOpen={props.isOpen}
        isRequired={props.isRequired}
        size={props.size}
      />
    ),
  },
)
