import React from "react"
import { FeaturedIcon } from "./featured-icons"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FeaturedIcon,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1102%3A5338",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("🔀 Icon swap"),
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
      }),
      color: figma.enum("Color", {
        Brand: "brand",
        Gray: "gray",
        Success: "success",
        Warning: "warning",
        Error: "error",
      }),
      // No matching props could be found for these Figma properties:
      // "iconSwap": figma.instance('🔀 Icon swap'),
      // "gradientMask": figma.boolean('Gradient mask'),
      // "type": figma.enum('Type', {
      //   "Light": "light",
      //   "Gradient": "gradient",
      //   "Dark": "dark",
      //   "Modern": "modern",
      //   "Modern neue": "modern-neue"
      // })
    },
    example: (props) => (
      <FeaturedIcon icon={props.icon} size={props.size} color={props.color} />
    ),
  },
)
