import React from "react"
import { PaginationPageDefault, PaginationPageDefault } from "./pagination"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PaginationPageDefault,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1334%3A1305",
  {
    props: {},
    example: (props) => <PaginationPageDefault />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PaginationPageDefault,
  "https://www.figma.com/design/aNpVcEB1GGkyKSzMAs8Ba8/%E2%9D%96-Untitled-UI---Pro-Variables-v7.0--COPY-?node-id=1115%3A68622",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "type": figma.enum('Type', {
      //   "Page default": "page-default",
      //   "Page minimal center aligned": "page-minimal-center-aligned",
      //   "Card default": "card-default",
      //   "Card minimal right aligned": "card-minimal-right-aligned",
      //   "Card minimal left aligned": "card-minimal-left-aligned",
      //   "Card button group right aligned": "card-button-group-right-aligned",
      //   "Card button group left aligned": "card-button-group-left-aligned",
      //   "Card button group center aligned": "card-button-group-center-aligned",
      //   "Card minimal center aligned": "card-minimal-center-aligned"
      // }),
      // "shape": figma.enum('Shape', {
      //   "Square": "square",
      //   "Circle": "circle"
      // }),
      // "breakpoint": figma.enum('Breakpoint', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => <PaginationPageDefault />,
  },
)
